twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        images_profil: "/img/profil/"
        images: "/img/"
when@test:
    twig:
        strict_variables: true
